### ISSUE TITLE
Homeassistant 2024.12.1 complains about "Error while setting up xsense platform for button"

### ISSUE THREAD

**Issue by allcoolusernamesaregone** [Jarnsen/ha-xsense-component_test#13]
Hi,

after updating to 2024.12.1, I see this error in the logs while starting up. I don't know if this was the case in the previous hass version (2024.8), but anyway, maybe someone knows what to fix or to do?

2024-12-10 13:43:09.369 ERROR (MainThread) [homeassistant.components.button] Error while setting up xsense platform for button
Traceback (most recent call last):
  File "/opt/homeassistant/lib/python3.12/site-packages/homeassistant/helpers/entity_platform.py", line 366, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/home/homeassistant/.homeassistant/custom_components/xsense/button.py", line 61, in async_setup_entry
    devices.extend(
  File "/home/homeassistant/.homeassistant/custom_components/xsense/button.py", line 66, in <genexpr>
    if description.exists_fn(dev, coordinator.xsense)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/homeassistant/.homeassistant/custom_components/xsense/button.py", line 31, in <lambda>
    exists_fn=lambda entity, xsense: xsense.has_action(entity, "test"),
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homeassistant/lib/python3.12/site-packages/xsense/base.py", line 230, in has_action
    return any(a for a in entity_def.get('actions', []) if a.get('action') == action)
                          ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by trollix** [comment]
Hello,
Same for me in HA 2024.12.4:

Enregistreur: homeassistant.components.button
Source: helpers/entity_platform.py:366
intégration: Bouton (documentation, problèmes)
S'est produit pour la première fois: 17:42:16 (1 occurrences)
Dernier enregistrement: 17:42:16

Error while setting up xsense platform for button
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 366, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/xsense/button.py", line 61, in async_setup_entry
    devices.extend(
    ~~~~~~~~~~~~~~^
        XSenseButtonEntity(
        ^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
        if description.exists_fn(dev, coordinator.xsense)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/config/custom_components/xsense/button.py", line 66, in <genexpr>
    if description.exists_fn(dev, coordinator.xsense)
       ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xsense/button.py", line 31, in <lambda>
    exists_fn=lambda entity, xsense: xsense.has_action(entity, "test"),
                                     ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/xsense/base.py", line 230, in has_action
    return any(a for a in entity_def.get('actions', []) if a.get('action') == action)
                          ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
